require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HuertosController do

  # This should return the minimal set of attributes required to create a valid
  # Huerto. As you add validations to Huerto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HuertosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all huertos as @huertos" do
      huerto = Huerto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:huertos).should eq([huerto])
    end
  end

  describe "GET show" do
    it "assigns the requested huerto as @huerto" do
      huerto = Huerto.create! valid_attributes
      get :show, {:id => huerto.to_param}, valid_session
      assigns(:huerto).should eq(huerto)
    end
  end

  describe "GET new" do
    it "assigns a new huerto as @huerto" do
      get :new, {}, valid_session
      assigns(:huerto).should be_a_new(Huerto)
    end
  end

  describe "GET edit" do
    it "assigns the requested huerto as @huerto" do
      huerto = Huerto.create! valid_attributes
      get :edit, {:id => huerto.to_param}, valid_session
      assigns(:huerto).should eq(huerto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Huerto" do
        expect {
          post :create, {:huerto => valid_attributes}, valid_session
        }.to change(Huerto, :count).by(1)
      end

      it "assigns a newly created huerto as @huerto" do
        post :create, {:huerto => valid_attributes}, valid_session
        assigns(:huerto).should be_a(Huerto)
        assigns(:huerto).should be_persisted
      end

      it "redirects to the created huerto" do
        post :create, {:huerto => valid_attributes}, valid_session
        response.should redirect_to(Huerto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved huerto as @huerto" do
        # Trigger the behavior that occurs when invalid params are submitted
        Huerto.any_instance.stub(:save).and_return(false)
        post :create, {:huerto => { "name" => "invalid value" }}, valid_session
        assigns(:huerto).should be_a_new(Huerto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Huerto.any_instance.stub(:save).and_return(false)
        post :create, {:huerto => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested huerto" do
        huerto = Huerto.create! valid_attributes
        # Assuming there are no other huertos in the database, this
        # specifies that the Huerto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Huerto.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => huerto.to_param, :huerto => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested huerto as @huerto" do
        huerto = Huerto.create! valid_attributes
        put :update, {:id => huerto.to_param, :huerto => valid_attributes}, valid_session
        assigns(:huerto).should eq(huerto)
      end

      it "redirects to the huerto" do
        huerto = Huerto.create! valid_attributes
        put :update, {:id => huerto.to_param, :huerto => valid_attributes}, valid_session
        response.should redirect_to(huerto)
      end
    end

    describe "with invalid params" do
      it "assigns the huerto as @huerto" do
        huerto = Huerto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Huerto.any_instance.stub(:save).and_return(false)
        put :update, {:id => huerto.to_param, :huerto => { "name" => "invalid value" }}, valid_session
        assigns(:huerto).should eq(huerto)
      end

      it "re-renders the 'edit' template" do
        huerto = Huerto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Huerto.any_instance.stub(:save).and_return(false)
        put :update, {:id => huerto.to_param, :huerto => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested huerto" do
      huerto = Huerto.create! valid_attributes
      expect {
        delete :destroy, {:id => huerto.to_param}, valid_session
      }.to change(Huerto, :count).by(-1)
    end

    it "redirects to the huertos list" do
      huerto = Huerto.create! valid_attributes
      delete :destroy, {:id => huerto.to_param}, valid_session
      response.should redirect_to(huertos_url)
    end
  end

end
