require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrecontratosController do

  # This should return the minimal set of attributes required to create a valid
  # Precontrato. As you add validations to Precontrato, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "suministro_cups" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrecontratosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all precontratos as @precontratos" do
      precontrato = Precontrato.create! valid_attributes
      get :index, {}, valid_session
      assigns(:precontratos).should eq([precontrato])
    end
  end

  describe "GET show" do
    it "assigns the requested precontrato as @precontrato" do
      precontrato = Precontrato.create! valid_attributes
      get :show, {:id => precontrato.to_param}, valid_session
      assigns(:precontrato).should eq(precontrato)
    end
  end

  describe "GET new" do
    it "assigns a new precontrato as @precontrato" do
      get :new, {}, valid_session
      assigns(:precontrato).should be_a_new(Precontrato)
    end
  end

  describe "GET edit" do
    it "assigns the requested precontrato as @precontrato" do
      precontrato = Precontrato.create! valid_attributes
      get :edit, {:id => precontrato.to_param}, valid_session
      assigns(:precontrato).should eq(precontrato)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Precontrato" do
        expect {
          post :create, {:precontrato => valid_attributes}, valid_session
        }.to change(Precontrato, :count).by(1)
      end

      it "assigns a newly created precontrato as @precontrato" do
        post :create, {:precontrato => valid_attributes}, valid_session
        assigns(:precontrato).should be_a(Precontrato)
        assigns(:precontrato).should be_persisted
      end

      it "redirects to the created precontrato" do
        post :create, {:precontrato => valid_attributes}, valid_session
        response.should redirect_to(Precontrato.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved precontrato as @precontrato" do
        # Trigger the behavior that occurs when invalid params are submitted
        Precontrato.any_instance.stub(:save).and_return(false)
        post :create, {:precontrato => { "suministro_cups" => "invalid value" }}, valid_session
        assigns(:precontrato).should be_a_new(Precontrato)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Precontrato.any_instance.stub(:save).and_return(false)
        post :create, {:precontrato => { "suministro_cups" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested precontrato" do
        precontrato = Precontrato.create! valid_attributes
        # Assuming there are no other precontratos in the database, this
        # specifies that the Precontrato created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Precontrato.any_instance.should_receive(:update_attributes).with({ "suministro_cups" => "MyString" })
        put :update, {:id => precontrato.to_param, :precontrato => { "suministro_cups" => "MyString" }}, valid_session
      end

      it "assigns the requested precontrato as @precontrato" do
        precontrato = Precontrato.create! valid_attributes
        put :update, {:id => precontrato.to_param, :precontrato => valid_attributes}, valid_session
        assigns(:precontrato).should eq(precontrato)
      end

      it "redirects to the precontrato" do
        precontrato = Precontrato.create! valid_attributes
        put :update, {:id => precontrato.to_param, :precontrato => valid_attributes}, valid_session
        response.should redirect_to(precontrato)
      end
    end

    describe "with invalid params" do
      it "assigns the precontrato as @precontrato" do
        precontrato = Precontrato.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Precontrato.any_instance.stub(:save).and_return(false)
        put :update, {:id => precontrato.to_param, :precontrato => { "suministro_cups" => "invalid value" }}, valid_session
        assigns(:precontrato).should eq(precontrato)
      end

      it "re-renders the 'edit' template" do
        precontrato = Precontrato.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Precontrato.any_instance.stub(:save).and_return(false)
        put :update, {:id => precontrato.to_param, :precontrato => { "suministro_cups" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested precontrato" do
      precontrato = Precontrato.create! valid_attributes
      expect {
        delete :destroy, {:id => precontrato.to_param}, valid_session
      }.to change(Precontrato, :count).by(-1)
    end

    it "redirects to the precontratos list" do
      precontrato = Precontrato.create! valid_attributes
      delete :destroy, {:id => precontrato.to_param}, valid_session
      response.should redirect_to(precontratos_url)
    end
  end

end
